# This github OAuth client will be used for authentication. Create
# one at https://github.com/organizations/ACCOUNT/settings/applications
SESSION_COOKIE_NAME = '__Host-sess'

PREFERRED_URL_SCHEME = 'https'

# info-beamer API keys.
# This key needs access to setups and assets as well as the
# node-message calls. If you consider the host running this
# code trusted, you might use a key with full account access.
# The keys given out to users are adhoc keys based on this key.
HOSTED_API_KEY = ''

# Maximum uploads per user unless exempt by being an admin or no-limit
# user
MAX_UPLOADS = 5

# list of users with elevated permissions. scheme is
# "oauthprovider:username" ("c3voc:exampleuser")
ADMIN_USERS = []
NO_LIMIT_USERS = []

# alternatively, you can provide json files which contain lists of admins
# and no-limit users. If you do so, you have to omit the non-json keys,
# otherwise the files will get ignored.
ADMIN_USERS_JSON = "admins.json"
NO_LIMIT_USERS_JSON = "no-limit.json"

# Setup IDs using the scheduled player setup. One of the
# playlists must be named 'User Content'. Its pages will be
# autogenerated by the CMS when calling /sync
SETUP_IDS = [
    212947,
]

# Generate some random string. It's used for signing
# urls send to moderators.
URL_KEY = 'reallysecure'

# redis is used as session store and for caching the asset list
REDIS_HOST = 'localhost'

# Unix timestamp allows for specifying start/end time
# of uploaded content
TIME_MIN = 1640039559
TIME_MAX = 1640905200

# change this to invalidate cached static files.
VERSION = 1

# configure fade in/out time for slides
FADE_TIME = 0.5


# Push notifications for moderation requests. Supports MQTT with a
# c3voc-style notification client and [NTFY](https://ntfy.sh/).
[NOTIFIER]
# configure on which minute of the hour the hourly reminder of assets
# pending moderation gets sent. Set to -1 to disable.
#ALERT_MINUTE = 7

# configure mqtt alerts
#MQTT_HOST = '127.0.0.1'
#MQTT_USERNAME = ''
#MQTT_PASSWORD = ''
#MQTT_TOPIC = '/voc/alert'

# configure alerts on ntfy
#NTFY = [
#    "https://ntfy.example.com/infobeamer-cms",
#]


# contact details
[FAQ]
SOURCE = "https://github.com/voc/infobeamer-cms"
CONTACT = """
    Please use the <a href="https://webirc.hackint.org/#ircs://irc.hackint.org/#infobeamer">IRC
    Channel #infobeamer on irc.hackint.org</a> (also
    <a href="https://www.hackint.org/transport/matrix">bridged to matrix</a>)
    or #info-beamer on the cccv rocketchat instance.
"""


# oauth providers
[oauth2_providers.github]
client_id = ""
client_secret = ""

[oauth2_providers.c3voc]
client_id = ""
client_secret = ""


# extra assets. If this is empty, only the uploaded content and a notice
# on where to find the CMS will be shown. You can use this to overlay
# content on top of that content.
[[EXTRA_ASSETS]]
type = "image"
asset = 828107 # fairydust
# bottom left,  10px from border
x1 = 10
y1 = 1004
x2 = 110
y2 = 1070

# rooms. This is both used for the /last view as well
# as the interruption control on /interrupt.
[[ROOMS]]
name = "Chaos-West TV"
device_id = 17968

[[ROOMS.interrupts]]
name = "Signal"
data = "signal"

[[ROOMS]]
name = "infobeamer stream"
device_id = 15586

[[ROOMS.interrupts]]
name = "Signal"
data = "signal"
